/* Auto-generated by bin2c.py from rom-l_8k.bin */

#ifndef ROM_L_H
#define ROM_L_H

#include <stdio.h>

extern const unsigned char rom_l[];
extern const unsigned int rom_l_size;

#endif /* ROM_L_H */
