/* Auto-generated by bin2c.py from rom-u_8k.bin */

#ifndef ROM_U_H
#define ROM_U_H

#include <stdio.h>

extern const unsigned char rom_u[];
extern const unsigned int rom_u_size;

#endif /* ROM_U_H */
